#!/usr/bin/env bash

if [ $1 = "preprocess" ] 
then 
  shift
  python -u data_preprocess_CellNEST.py $@
elif [ $1 = "run" ]
then
  shift
  python -u run_CellNEST.py $@ 
elif [ $1 = "postprocess" ] 
then
  shift
  python -u output_postprocess_CellNEST.py $@
elif [ $1 = "postprocess_split" ] 
then
  shift
  python -u output_postprocess_CellNEST_split.py $@
elif [ $1 = "visualize" ] 
then
  shift
  python -u output_visualization_CellNEST.py $@
elif [ $1 = "interactive" ] 
then
  shift
  cd $1
  shift
  bash nest_interactive $@ 
elif [ $1 = "output_graph_picture" ] 
then
  shift
  bash dot_to_pdf_svg.sh $@
elif [ $1 = "relay_celltype" ] 
then
  shift
  python -u relay_cell_type.py $@
elif [ $1 = "relay_confidence" ] 
then
  shift
  python -u relay_confidence.py $@
elif [ $1 = "relay_extract" ] 
then
  shift
  python -u extract_relay_nest.py $@
elif [ $1 = "preprocess_intra" ] 
then
  shift
  python -u data_preprocess_intra_CellNEST.py $@
elif [ $1 = "preprocess_scrna" ] 
then
  shift
  python -u data_preprocess_CellNEST.py --data_type scrna $@
elif [ $1 = "preprocess_lrpair_mae_scrna" ]
then
  shift
  python -u data_preprocess_lrpair_mae_scrna_CellNEST.py $@
elif [ $1 = "run_lrpair_mae_scrna" ]
then
  shift
  python -u run_CellNEST_lrpair_mae_scrna.py $@
elif [ $1 = "cluster_lrpair_mae" ]
then
  shift
  python -u cluster_lrpair_mae_modules.py $@
elif [ $1 = "downstream" ] 
then
  shift
  python -u plot_downstream_genes.py $@
elif [ $1 = "confidence_interval" ] 
then
  shift
  python -u confidence_interval_CellNEST.py $@
fi


